"""empty message

Revision ID: a8d5bd0ad975
Revises: 
Create Date: 2025-11-20 23:31:03.173224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d5bd0ad975'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('genre_id'),
    sa.UniqueConstraint('genre_name')
    )
    op.create_table('login',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('mood',
    sa.Column('mood_id', sa.Integer(), nullable=False),
    sa.Column('mood_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('mood_id'),
    sa.UniqueConstraint('mood_name')
    )
    op.create_table('song',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('mood_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['mood_id'], ['mood.mood_id'], ),
    sa.PrimaryKeyConstraint('song_id'),
    sa.UniqueConstraint('spotify_id')
    )
    op.create_table('user_liked_songs',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('date_liked', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.song_id'], ),
    sa.ForeignKeyConstraint(['username'], ['login.username'], ),
    sa.PrimaryKeyConstraint('username', 'song_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_liked_songs')
    op.drop_table('song')
    op.drop_table('mood')
    op.drop_table('login')
    op.drop_table('genre')
    # ### end Alembic commands ###
